### ISSUE TITLE
请问如何跳转网址

### ISSUE THREAD

**Issue by APAO002** [bo-blog/bw#103]
之前因为程式中栏位：Target 过于严谨，于是把
https://plant.apaostudio.com/read.php/shan-ying-hua--han-fei-ying---------/
（这似乎是被固定跳至首页）
![image 002](https://user-images.githubusercontent.com/38335882/51541180-261d7000-1e93-11e9-940e-ab03c1f4adf2.png)

把网址改成这个的时候，却发生搜寻引擎的暂存（已解决）或是有人把连结笔记起来
https://plant.apaostudio.com/read.php/shan-ying-hua
但是看后台，还是常常有人连结到旧的网址，请问如何解决转址问题呢？

**Comment by bo-blog** [comment]
好像只能等搜索引擎更新。也可以用URL Rewrite写个规则，这个属于服务器端的设置了。
