### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by uno55555** [bo-blog/bw#111]
打扰大家了。今天按照文档安装，遇到了目前最大的问题：
1.  url填什么？
![image](https://user-images.githubusercontent.com/43940742/70221235-f281c680-1782-11ea-983b-7f70d0986348.png)
之前安装好了SQLite，以及PHP（pdo和crul）均开启。
2. 不知道bw的安装包应该解压到哪里呢？文档上的服务器是指？
![image](https://user-images.githubusercontent.com/43940742/70221489-691ec400-1783-11ea-8210-c60b9df1cd84.png)
不懂这些配置，可能问了些小小白问题，但之前有搜索过，没能解答我的疑惑，还望能有同志帮忙解答，或者作者有空回复一下。
感谢！: )

**Comment by bo-blog** [comment]
你可能需要先了解一些必要的基础知识。先看下这篇：https://yihui.org/cn/2009/06/how-to-build-a-website-as-a-dummy/

**Comment by uno55555** [comment]
> 你可能需要先了解一些必要的基础知识。先看下这篇：https://yihui.org/cn/2009/06/how-to-build-a-website-as-a-dummy/
你好，很抱歉现在才回复。文章我已经看了，了解了一些基本信息，对我很有帮助。之前我其实也看了一些文章，知道大概需要购买域名，服务器等；我觉得有些麻烦，这么说我的需求吧：我想要这样一个博客，他的获取方式十分简便，他可能依托于某个平台，但是他又有自己的独立性，不会随着平台的改动而发生比较大的变动。就好像我能轻松的像注册新浪博客或者博客园一样，但是新浪无权干涉我的博客。 我起初以为您的作品提供的就是这样一个东西，就好像Mastodon社区一样。又在胡说八道了我，所以很抱歉这么晚回复。谢谢您的及时回复，相比之下，我真是太不尊重人了，我感到惭愧！

**Comment by bo-blog** [comment]
针对你的需求，如果独立建站的难度太高，有那么几个方案。

1. 一些非墙内企业的写作平台或博客托管服务
Medium：https://medium.com/ （需要翻墙）
Typlog： https://typlog.com/  （需要付费）

2. 基于Github Pages的工具
目前上手门槛最低的是Gridea：https://gridea.dev/

希望对你有帮助。

**Comment by ZERO4579** [comment]
> 针对你的需求，如果独立建站的难度太高，有那么几个方案。
> 
> 
> 一些非墙内企业的写作平台或博客托管服务
> Medium：https://medium.com/ （需要翻墙）
> Typlog： https://typlog.com/  （需要付费）
> 
> 
> 基于Github Pages的工具
> 目前上手门槛最低的是Gridea：https://gridea.dev/
> 
> 
> 希望对你有

**Comment by uno55555** [comment]
> 针对你的需求，如果独立建站的难度太高，有那么几个方案。
> 
> 
> 一些非墙内企业的写作平台或博客托管服务
> Medium：https://medium.com/ （需要翻墙）
> Typlog： https://typlog.com/  （需要付费）
> 
> 
> 基于Github Pages的工具
> 目前上手门槛最低的是Gridea：https://gridea.dev/
> 
> 
> 希望对你有帮助。

 好的，墙外的不太方便，之前也有看到过Gridea，那我去尝试一下吧。十分感谢您的耐心回复！
