### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by qyj229** [bo-blog/bw#15]
我使用万网的云基础服务器，文章超过20篇下一篇文章在后台就显示不了，点下一页也没用，以前以为是自己把数据库搞乱了，趁着程序升级我重新装了一遍还是这样。前台可以显示。

**Comment by bo-blog** [comment]
麻烦贴个截图，不能打开的提示是什么

**Comment by qyj229** [comment]
![1](https://cloud.githubusercontent.com/assets/11073977/10408794/18ac39c0-6f3b-11e5-9f0f-2b152e793b08.png)
![2](https://cloud.githubusercontent.com/assets/11073977/10408796/1f60ac4c-6f3b-11e5-91ef-c57f5746123f.png)

**Comment by qyj229** [comment]
我以前就这情况，这次彻底重装，文章都是我手工一篇一篇的加上去的，加到21篇我就测试了下，还是原样，我现在都不敢再加了。

**Comment by bo-blog** [comment]
推断是服务器的兼容性问题。
试下这个附件(去掉.txt的后缀名后放到inc/下覆盖原文件）
[mode_admin.php.txt](https://github.com/bo-blog/bw/files/11156/mode_admin.php.txt)

**Comment by qyj229** [comment]
谢谢，这个问题解决了。
