### ISSUE TITLE
数据库备份的问题。

### ISSUE THREAD

**Issue by qyj229** [bo-blog/bw#16]
![3](https://cloud.githubusercontent.com/assets/11073977/10408852/3a98ba6c-6f3c-11e5-9395-b7353ffcbfd7.png)
![4](https://cloud.githubusercontent.com/assets/11073977/10408855/408b7144-6f3c-11e5-9fad-134783d4a1b5.png)
点完备份显示空白页，我这是全新安装，啥也没动。

**Comment by bo-blog** [comment]
在上上个版本备份功能被暂时移除前，点击这个链接有反应吗？

**Comment by qyj229** [comment]
上上个版本没问题，但那时是在阿里云服务器里。换到万网服务器之时已经升级到你那个去掉备份的版本了，所以不知道有没有效。

**Comment by bo-blog** [comment]
因一处文件引用错误导致。下一版修复。
