### ISSUE TITLE
后台友情链接不能有空格

### ISSUE THREAD

**Issue by lynca** [bo-blog/bw#32]
后台友情链接管理里，前面的链接地址不能带有参数，后面的名字不能有2个及2个以上空格。否则会Internal Server Error。

**Comment by lynca** [comment]
用SQLite模式安装后显示500 Internal Server Error，无法打开，用mysql没有问题，这是为何啊？进文件管理器里发现安装后的数据库文件在install文件夹里，而不是在conf文件夹里，会是这个原因吗？但是我自行把数据库移动到其他文件夹还是不行。

**Comment by lynca** [comment]
conf\info.php内的“siteURL”，即基本设置里的根网址后若带有"/"会导致无法登录后台。

**Comment by bo-blog** [comment]
1. 收到
2. 确保你安装时填写的路径是想要存放的sq3文件的正确路径而且这个目录要有写入权限。
3. 填写时的确最后不能有/，不然URL就是  ...//了，是会报错的。

**Comment by lynca** [comment]
> 确保你安装时填写的路径是想要存放的sq3文件的正确路径而且这个目录要有写入权限。
意思是说填写的sq3文件必须包含文件路径？那是相对路径还是绝对路径呢？比如说填“conf/data.data"这样的可以吗？

**Comment by bo-blog** [comment]
一般是写完整路径的。比如/etc/public_html/abcd.sq3 或者 c://apache/htdocs/abcd.sq3

**Comment by lynca** [comment]
貌似很多主机都是只知道“/域名/public_html/"或“/httpdocs/”这样的路径，是否可以修改一下，让数据库默认存放在“conf/”内？这样应该可以减少很多安装时的困惑，而且可以直接和配置文件一起备份。

**Comment by bo-blog** [comment]
相对路径应该也是没有问题的啊。这里用到的是PHP内置的SQL支持，程序没有干预任何路径的判断。internal error多半是权限原因。

**Comment by lynca** [comment]
同样的问题，现在新版本的友情链接里站名有两个空格时，前台友情链接无法显示，后台参数设置“Internal Server Error”。

**Comment by lynca** [comment]
刚才重新试了一下SQLite模式安装，用相对路径还是无法安装，用绝对路径成功安装。

**Comment by lynca** [comment]
当文章数为零时，前台及文章管理页面

> 出现错误： 该页尚不存在。您可能访问了一个尚未添加任何内容的分类或页面。

**Comment by bo-blog** [comment]
@lynca 空格的bug测试不出来。两个空格的站名测试下来没有问题。
<img width="270" alt="default" src="https://cloud.githubusercontent.com/assets/5775403/13546159/e518c664-e2df-11e5-8b7b-cfae6e29611b.PNG">
<img width="231" alt="222" src="https://cloud.githubusercontent.com/assets/5775403/13546160/e51c2b7e-e2df-11e5-9141-3a1f95c024d7.PNG">

**Comment by lynca** [comment]
![_2016-03-06t01-41-53 427z](https://cloud.githubusercontent.com/assets/14791129/13551784/23079724-e381-11e5-8c05-7a027f875c67.png)

![default](https://cloud.githubusercontent.com/assets/14791129/13551770/aaec75b6-e380-11e5-8905-66da38912eba.PNG)
![1](https://cloud.githubusercontent.com/assets/14791129/13551819/da11ec3a-e381-11e5-8933-64d480798af6.PNG)

**Comment by lynca** [comment]
![_2016-03-06t02-07-33 519z](https://cloud.githubusercontent.com/assets/14791129/13551871/68553672-e383-11e5-97f6-bd0b18f6ea6e.png)

**Comment by bo-blog** [comment]
OK, 修好了。See you in 1.0.6
