### ISSUE TITLE
安装无成后出现代码错误”inc/system.php on line 901“

### ISSUE THREAD

**Issue by dqcser** [bo-blog/bw#34]
提示“inc/system.php on line 901”。用的免空测试，SQLite安装的，表前缀用了“BW_”
网址：www.mfee.net

**Comment by bo-blog** [comment]
你这个没装成功啊。数据库也没创建。

**Comment by dqcser** [comment]
这样子，谢谢，我再试试看，我见提示说安装成功的。。
