### ISSUE TITLE
添加分类报错

### ISSUE THREAD

**Issue by ffyfyff** [bo-blog/bw#44]
Database Error: 42S22, 1054, Unknown column 'aCateTheme' in 'field list'

**Comment by bo-blog** [comment]
不好意思，1.0.7改了数据库结构，安装文件没同步更新。会尽快更新，到时请重装。

**Comment by ffyfyff** [comment]
那添加的文章怎么办啊，会丢失吗？反馈个问题，bw的速度很快，这个很喜欢，但是现在没搜索，找文章费点劲


来自 魅蓝 note

-------- 原始邮件 --------
发件人：bo-blog <notifications@github.com>
时间：周三 5月18日 00:11
收件人：bo-blog/bw <bw@noreply.github.com>
抄送：zuicms <ffyfyff@163.com>,Author <author@noreply.github.com>
主题：Re: [bo-blog/bw] 添加分类报错 (#44)

**Comment by qyj229** [comment]
没搜索，找文章费点劲,这倒是事实，也没分页，文章多是个问题。

**Comment by bo-blog** [comment]
可以手动执行下数据库。
Sqlite:
ALTER TABLE categories ADD COLUMN aCateTheme VARCHAR (255)
Mysql:
ALTER TABLE categories ADD aCateTheme VARCHAR (255)

**Comment by ffyfyff** [comment]
好的3Q


来自 魅蓝 note

-------- 原始邮件 --------
发件人：bo-blog <notifications@github.com>
时间：周三 5月18日 23:06
收件人：bo-blog/bw <bw@noreply.github.com>
抄送：zuicms <ffyfyff@163.com>,Author <author@noreply.github.com>
主题：Re: [bo-blog/bw] 添加分类报错 (#44)

**Comment by ffyfyff** [comment]
多说怎么用，框里填什么？
反馈个小问题，修改七牛域名的时候，有时会存不上，多试几次就好了。
还有已经小建议 输入框下面能给个链接示例不！
输入七牛域名加http://的好些，不加虽然也能用，传图片时不是要往里填地址吗，没http的不会显示的，加了方便填图片地址






在 2016-05-18 23:24:39，"ffyfyff" <ffyfyff@163.com> 写道：

好的3Q




来自 魅蓝 note



-------- 原始邮件 --------
发件人：bo-blog <notifications@github.com>
时间：周三 5月18日 23:06
收件人：bo-blog/bw <bw@noreply.github.com>
抄送：zuicms <ffyfyff@163.com>,Author <author@noreply.github.com>
主题：Re: [bo-blog/bw] 添加分类报错 (#44)



可以手动执行下数据库。
Sqlite:
ALTER TABLE categories ADD COLUMN aCateTheme VARCHAR (255)
Mysql:
ALTER TABLE categories ADD aCateTheme VARCHAR (255)

**Comment by bo-blog** [comment]
多说设置参考： http://www.bo-blog.com/bw/post/cloud-services/
