### ISSUE TITLE
WIN7搭建的本地环境，不能安装最新版本的BW，求助！

### ISSUE THREAD

**Issue by dqcser** [bo-blog/bw#45]
搭建的环境参数，已截图：http://oi66.tinypic.com/6oofb4.jpg
安装BW时，就出来第一步，选择语言，然后按什么都没有反应了，请求助，是缺少了什么组件支持还是什么？

**Comment by bo-blog** [comment]
理论上你这个配置没问题的。最好贴PHPINFO，这种探针缺少信息。

**Comment by dqcser** [comment]
简单概述下：
Win7 64位，UPUPW的Apache环境包（本人新手，利用套件）
再将MySQL替换掉MariaDB
PHPINFO做成了HTML，打包放上度盘：http://pan.baidu.com/s/1boXjXDl

大大有时间就帮我看看吧，谢谢。
PS：很喜欢BW的简洁，1.0.7版本可用于正式博客吗？想替换掉现有的博客程序。

**Comment by bo-blog** [comment]
环境没问题。刚才更新了下 install/下面的文件，修改了几个错误，可以下载下来再试试。

1.0.7作为博客基本功能都有了，用来正式开博是没问题，但旧数据还没法转换。

**Comment by dqcser** [comment]
感谢，我再试试
