### ISSUE TITLE
求助新问题nginx的伪静态

### ISSUE THREAD

**Issue by ffyfyff** [bo-blog/bw#46]
用在线apache转nginx转的
location / {
if (-f $request_filename){
	set $rule_0 1;
}
if (-d $request_filename){
	set $rule_0 1;
}
if ($rule_0 = "1"){
#ignored: "-" thing used or unknown variable in regex/rew 
}
	rewrite ^/index/([0-9]+)/?$ /index.php/$1/ last;
	rewrite ^/category/([^/]+)/([0-9]+)/?$ /category.php/$1/$2/ last;
	rewrite ^/category/([^/]+)/?$ /category.php/$1/ last;
	rewrite ^/post/([^/]+)/?$ /read.php/$1/ last;
	rewrite ^/tag/([^/]+)/([0-9]+)/?$ /tag.php/$1/$2/ last;
	rewrite ^/tag/([^/]+)/?$ /tag.php/$1/ last;
}
使用后 一直都是404错误，后台能上，但是系统设置什么的也都是 404

**Comment by kooker** [comment]
```
        rewrite ^/index/([0-9]+)/?$ /index.php?go=/$1/ break;
        rewrite ^/category/([^/]+)/([0-9]+)/?$ /category.php?go=/$1/$2/ break;
        rewrite ^/category/([^/]+)/?$ /category.php?go=/$1/ break;
        rewrite ^/post/([^/]+)/?$ /read.php?go=/$1/ break;
        rewrite ^/tag/([^/]+)/([0-9]+)/?$ /tag.php?go=/$1/$2/ break;
        rewrite ^/tag/([^/]+)/?$ /tag.php?go=/$1/ last;
```

修改inc/bw.inc.php 47-55 行为

```
		} elseif (FORCE_UGLY_URL == 0 || (self :: $conf['linkPrefixIndex'] == 'index.php' && false !==stripos ($_SERVER['SERVER_SOFTWARE'], 'nginx'))) {
			self :: $conf['linkPrefixCategory'] = 'category';
			self :: $conf['linkPrefixArticle'] = 'post';
			self :: $conf['linkPrefixTag'] = 'tag';
			self :: $conf['linkPrefixSend'] = 'send.php?go=';
			self :: $conf['linkPrefixAdmin'] = 'admin.php?go=';
			self :: $conf['linkPrefixPage'] = 'page';
			self :: $conf['linkConj'] = '&';
		} else {
			self :: $conf['linkPrefixCategory'] = 'category';
			self :: $conf['linkPrefixArticle'] = 'post';
			self :: $conf['linkPrefixTag'] = 'tag';
			self :: $conf['linkPrefixSend'] = 'send.php';
			self :: $conf['linkPrefixAdmin'] = 'admin.php';
			self :: $conf['linkPrefixPage'] = 'page';
			self :: $conf['linkConj'] = '?';
		}

```

**Comment by bo-blog** [comment]
if (!-e $request_filename)
       {
          rewrite ^/YOUR_PATH_HERE/index/([0-9]+)?/$ /YOUR_PATH_HERE/index.php?go=/$1 last;
          rewrite ^/YOUR_PATH_HERE/post/(.+)?/$ /YOUR_PATH_HERE/read.php?go=/$1 last;
          rewrite ^/YOUR_PATH_HERE/category/(.+)?/$ /YOUR_PATH_HERE/category.php?go=/$1 last;
          rewrite ^/YOUR_PATH_HERE/category/(.+)/([0-9]+)?/$ /YOUR_PATH_HERE/category.php?go=/$1/$2 last;
          rewrite ^/YOUR_PATH_HERE/tag/(.+)?/$ /YOUR_PATH_HERE/tag.php?go=/$1 last;
          rewrite ^/YOUR_PATH_HERE/tag/(.+)/([0-9]+)?/$ /YOUR_PATH_HERE/tag.php?go=/$1/$2 last;
          rewrite ^/YOUR_PATH_HERE/send.php/(.+)$ /YOUR_PATH_HERE/send.php?go=/$1 last;
          rewrite ^/YOUR_PATH_HERE/admin.php/(.+)$ /YOUR_PATH_HERE/admin.php?go=/$1 last;
          rewrite ^/YOUR_PATH_HERE/page/(.+)?/$ /YOUR_PATH_HERE/page.php?go=/$1 last;
     }

请把 **YOUR_PATH_HERE** 替换成真实安装路径，例如 /blog/ 。

**Comment by bo-blog** [comment]
@kooker Haha，有些环境对中文URL有兼容问题的。

**Comment by ffyfyff** [comment]
@kooker haha 感谢台湾的朋友
@bo-blog 已经重新安装了1.0.8 并且使用了伪静态 完美运行
1.0.8-r是什么版本啊

**Comment by kooker** [comment]
@ffyfyff 

额 我是福建的

> 1.0.8-r是什么版本啊

https://github.com/bo-blog/bw/commit/30d309d4fdc7890ac74ac30795932a88097437ed

分离前后台 css 文件时没注意少了个样式
