### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by ffyfyff** [bo-blog/bw#47]
安装时检测上多加一条，
conf目录的可写入条件

**Comment by ffyfyff** [comment]
继续反馈
插件扩展安装主题没反应，估计是目录不可写
这个插件是传到什么目录里的，安装检测时可以检测下不
还有个问题是导出的伪静态不好使nginx的服务器点导出后显示404

**Comment by kooker** [comment]
@ffyfyff 
主题目录 theme
插件目录 extension
如果上传 .pkg 要先解压

导出默认主题显示404 这个还是环境问题吧 1.0.8 我的正常
Linux 2.6.32-573.12.1.el6.x86_64
nginx 1.10.0
php 7.0.6

**Comment by bo-blog** [comment]
插件在 extension，主题在 theme。

**Comment by bo-blog** [comment]
推测你这些问题都和权限有关。所有目录和子目录和文件都给777。

**Comment by ffyfyff** [comment]
777不安全吧


来自 魅蓝 note

-------- 原始邮件 --------
发件人：bo-blog <notifications@github.com>
时间：周一 5月30日 20:19
收件人：bo-blog/bw <bw@noreply.github.com>
抄送：zuicms <ffyfyff@163.com>,Mention <mention@noreply.github.com>
主题：Re: [bo-blog/bw] 反馈 (#47)

**Comment by bo-blog** [comment]
没啥不安全的。
