### ISSUE TITLE
PHP7下无法使用后台更新

### ISSUE THREAD

**Issue by kooker** [bo-blog/bw#48]
bW 1.0.7-r
nginx 1.10.0
php 7.0.6
curl 7.48.0

Warning: file_put_contents(./update/dlupkg_tmp.zip): failed to open stream: No such file or directory in /var/lib/openshift/56eba0c80c1e664bcf0000d9/app-root/runtime/repo/www/mode/admin.mod.php on line 496

Warning: md5_file(./update/dlupkg_tmp.zip): failed to open stream: No such file or directory in /var/lib/openshift/56eba0c80c1e664bcf0000d9/app-root/runtime/repo/www/mode/admin.mod.php on line 498

还有 ajax 后台 https 兼容性不好

**Comment by bo-blog** [comment]
update可写吗？

https的问题还是因为 bw.bo-blog.com 没有https -_-

**Comment by kooker** [comment]
我二了 原来是把 update 给删除
