### ISSUE TITLE
希望早日把后台登陆问题研究出来。

### ISSUE THREAD

**Issue by qyj229** [bo-blog/bw#50]
每次我登入后台我都要拨号N次，力求能分配到真实的外网IP地址。

**Comment by bo-blog** [comment]
这个难，没有这样的环境测试，是找不出原因的。

**Comment by bo-blog** [comment]
@qyj229 用这个 inc/system.php 替换一下，看下是不是解决了。

[system.zip](https://github.com/bo-blog/bw/files/310150/system.zip)

**Comment by qyj229** [comment]
@bo-blog 试了一下，还是原样，看你哪天有时间，我给你个远程协助看看，因为你没这样的环境测试。实在不行我就多拨几次号，也能进入。

**Comment by qyj229** [comment]
我是把后台缓存关闭了测试的。
这个是不能进入后台的环境：
![2](https://cloud.githubusercontent.com/assets/11073977/15985371/8765fa56-301d-11e6-9495-180899d4c5e2.jpg)
![3](https://cloud.githubusercontent.com/assets/11073977/15985373/8dbc9144-301d-11e6-9ad1-cde0d524d73c.jpg)
第一个图是路由器后台，两个IP不一样。

**Comment by qyj229** [comment]
这个是能进后台的环境：
![4](https://cloud.githubusercontent.com/assets/11073977/15985390/f94c0e62-301d-11e6-87ed-3f30661bf8e0.jpg)
![5](https://cloud.githubusercontent.com/assets/11073977/15985391/ff46f818-301d-11e6-9fc2-1c50fda0ef35.jpg)
两个IP一样了，就能进了，是不是后台程序有判断功能？。

**Comment by bo-blog** [comment]
分配到内网ip时，每次刷新探针，显示的伪外网ip会变吗？

**Comment by qyj229** [comment]
不会变

**Comment by bo-blog** [comment]
贴个不能登陆的后台报错的截图给我

**Comment by qyj229** [comment]
![1](https://cloud.githubusercontent.com/assets/11073977/15986145/ff634422-3032-11e6-849c-5b746a4c4620.jpg)

**Comment by bo-blog** [comment]
[admin.inc.zip](https://github.com/bo-blog/bw/files/318714/admin.inc.zip)
试试这个
inc/admin.inc.php

**Comment by qyj229** [comment]
@bo-blog 从第一个内测试版开始困扰我很久的问题解决了，无休止的重复拨号工作可以甩掉了。非常感谢。
