### ISSUE TITLE
..

### ISSUE THREAD

**Issue by huangjinjin914** [bo-blog/bw#52]
http://www.bo-blog.com/bw/
比如这个首页还少点的内容显示。

**Comment by qyj229** [comment]
你说的意思是文章截断符吧？就是在文章需要截断的地方加三个英文+号，+号后面的就不显示了。

**Comment by huangjinjin914** [comment]
谢谢。这是MarkDown的功能吗？

**Comment by huangjinjin914** [comment]
thx
