### ISSUE TITLE
请问如何手动升级bW

### ISSUE THREAD

**Issue by venusxx** [bo-blog/bw#59]
我现在BW的版本是1.0.2，但是点自动升级时弹出“出现错误： 下载更新文件压缩包失败。可能是服务器忙，或者当前服务器不支持 cURL。”

bW (ver 1.0.2)
Apache
PHP Version 5.4.45 

请问如何手动升级呢？谢谢！在coding那边也有提不过一直没回复，也不知道该去哪里问，先谢谢大家。

**Comment by qyj229** [comment]
@venusxx 现在是1.10了，你更新的太慢了吧。说明里手动更新的步骤：“请将手动更新包命名为 manual_update.zip 并上传至 /update/ 然后点击下方按钮。”

**Comment by venusxx** [comment]
@qyj229 谢谢！请问去哪里下载手动更新包呢？在官网找了一圈，只找到整个程序的下载。因为之前只搭了个框架，现在准备正式转过去，所以也一直没更新，现在更新就遇到了上述问题。

**Comment by qyj229** [comment]
你版本低了，估计没手动个更新那项，干脆重新安装一遍吧，BW重装比较简单，数据还不会丢失。

**Comment by venusxx** [comment]
@qyj229 谢谢，直接覆盖安装后OK了！
