### ISSUE TITLE
Mint这个模板无法显示评论及搜索框

### ISSUE THREAD

**Issue by venusxx** [bo-blog/bw#71]
只有Default的Breeze模板才能显示评论框和搜索框。

另外一旦点击搜索框，如果不想搜索，也无法退出搜索框

**Comment by bo-blog** [comment]
这个我更新好了，但bo-blog.com域名挂了，暂时穿不上去。

**Comment by bo-blog** [comment]
[theme_mint_V1.5.pkg.zip](https://github.com/bo-blog/bw/files/1116937/theme_mint_V1.5.pkg.zip)

传上来了，请解压后重装该主题（主题里先设置为default主题，移除Mint，重新安装Mint，重新启用。）

**Comment by qyj229** [comment]
@bo-blog 这个模板管理员留言没有头像。
![1](https://user-images.githubusercontent.com/11073977/28048693-272ede70-6625-11e7-94dd-8149dfe69662.png)

**Comment by bo-blog** [comment]
http://xiaofengtest.qiniudn.com/storage/49ffd34c_bw_theme_packages.zip
