### ISSUE TITLE
备份功能出现错误

### ISSUE THREAD

**Issue by EntityCat** [bo-blog/bw#86]
"备份为一个压缩文件"出现错误无法使用
提示此网站无法正常运作

**Comment by bo-blog** [comment]
SQLite还是MySQL？

**Comment by EntityCat** [comment]
MySQL,先下了

**Comment by bo-blog** [comment]
MySQL的备份用了一个第三方类库，兼容性没有深入测试过。如果实在用不了，可以自己装一个phpMyAdmin进行数据库备份。

**Comment by bo-blog** [comment]
第三方类已更新
