### ISSUE TITLE
文章名包含特殊字符的时候无法访问

### ISSUE THREAD

**Issue by EntityCat** [bo-blog/bw#91]
大概是做了url转码，比如#!+什么的没法访问
最好修一下这个bug吧...

**Comment by bo-blog** [comment]
哎。。。尽管后台那么大的字提示不要用特殊字符，但还是……下个版本做个检测吧，特殊字符一律不让提交。

**Comment by bo-blog** [comment]
1.6.0添加了检测防止设置错误的ID
