### ISSUE TITLE
tag 问题一直无法解决

### ISSUE THREAD

**Issue by APAO002** [bo-blog/bw#93]
网站
https://plant.apaostudio.com
问题URL
https://plant.apaostudio.com/tag.php/%E6%B5%B7%E5%B7%9E%E5%B8%B8%E5%B1%B1%E5%B1%AC/1/
tag
繁体中文「海州常山屬」简体中文「海州常山属」都會產生問題。
处理方法
删除tag后->储存->编辑加入tag->储存。问题还是存在。

**Comment by bo-blog** [comment]
麻烦导出一下 tags 表私信给我：
info@bo-blog.com
谢谢。

**Comment by bo-blog** [comment]
用这个替换一下 inc/article.inc.php
应该修复了删除Tag时可能导致的问题，以及对已经出现问题的Tag的容错。

建议你对含之前出错Tag的帖子增删一次Tag后重新保存：八仙花屬、大戟屬、婆婆納屬、海州常山屬、馬纓丹屬、鸡屎树属、鼠尾草屬
[article.inc.php.zip](https://github.com/bo-blog/bw/files/2363106/article.inc.php.zip)

**Comment by APAO002** [comment]
太感谢您了
